ERROR_SERVER = "Ошибка на стороне сервера"
ERROR_GET_CONTACTS = "Ошибка при получении контактов"
ERROR_ADD_TELEGRAM_MESSAGE = "Ошибка при добавлении сообщения из Telegram"
ERROR_ADD_VK_MESSAGE = "Ошибка при добавлении сообщения из VK"
ERROR_GET_TELEGRAM_MESSAGES = "Ошибка при получении сообщений Telegram из БД"
ERROR_GET_VK_MESSAGES = "Ошибка при получении сообщений ВК из БД"
ERROR_ADD_REQUEST_ANSWER = "Ошибка при добавлении запроса/ответа в БД"
ERROR_CLEAN_OLD_REQUESTS_ANSWERS = "Ошибка при очищении старых запросов/ответов в БД"